name    'treydock-gpg_key'
version '0.0.3'
source 'git://github.com/treydock/puppet-gpg_key.git'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'GPG key module'
description 'Custom type and provider to manage GPG keys'
project_page 'http://github.com/treydock/puppet-gpg_key'
