forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-concat', '2.2.0'
mod 'garethr-docker', '5.3.0'
mod 'stahnma-epel', '1.2.2'
mod 'puppetlabs-firewall', '1.8.2'
mod 'jhoblitt-ganglia', '2.2.0'
mod 'treydock-gpg_key', '0.0.4'
mod 'puppetlabs-mongodb', '0.17.0'
mod 'derdanne-nfs', '2.0.3'
mod 'puppet-nodejs', '2.3.0'
mod 'NeilHanlon-r', '0.1.0'
mod 'puppetlabs-stdlib', '4.16.0'
