Vagrant.configure(2) do |config|
  #config.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"
  config.vm.box = "puppetlabs/centos-7.2-64-puppet"
  config.ssh.insert_key = false
  #config.vm.network "private_network", ip: "172.17.9.55"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder "../../../prototipo", "/app"
  # config.vm.network "forwarded_port", guest: 25565, host: 25565
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.synced_folder "../../prototipo", "/app"
  # config.vm.provider "virtualbox" do |vb|
  #   vb.memory = "512"
  # end
  # vagrant ssh -c "hostname -I | cut -d' ' -f2" 2>/dev/null
end
