cluster = {
    :controller => {
        :hostname => "controller",
        :type => "controller"
    },
    :server1 => {
        :hostname => "server1",
        :type => "node"
    },
    #:server2 => {
    #    :hostname => "server2",
    #    :type => "node"
    #},
}

## vagrant plugin install vagrant-hostmanager
## vagrant plugin install vagrant-digitalocean
## vagrant up --provider=digital_ocean
## vagrant hostmanager --provider=digital_ocean
Vagrant.configure("2") do |global_config|
  #global_config.hostmanager.enabled = true
  #global_config.hostmanager.manage_guest = true
  #global_config.hostmanager.ignore_private_ip = false
  cluster.each_pair do |name, options|
    global_config.vm.define name do |config|
      config.vm.provision "shell", path: "installscript.sh"
      config.vm.hostname = "#{name}"
      config.vm.box = "centos/7"

      config.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--memory", "512"]
      end

      config.vm.provider :digital_ocean do |provider, override|
        override.ssh.private_key_path = '~/.ssh/id_rsa'
        override.vm.box = 'digital_ocean'
        provider.token = ENV["DOAPI"]
        provider.image = 'centos-7-x64'
        provider.region = 'nyc3'
        if options[:type] == "controller"
          provider.size = '1gb'
        else
          provider.size = '512mb'
        end
      end

      if options[:type] == "controller"
        config.vm.provision :puppet do |puppet|
          puppet.environment = "production"
          puppet.environment_path = "puppet"
          puppet.module_path = "puppet/production/modules"
          puppet.manifests_path = "puppet/production/manifests"
          puppet.manifest_file  = "controller.pp"
          puppet.options = "--verbose --debug"
        end
      elsif options[:type] == "node"
        config.vm.provision :puppet do |puppet|
          puppet.environment = "production"
          puppet.environment_path = "puppet"
          puppet.module_path = "puppet/production/modules"
          puppet.manifests_path = "puppet/production/manifests"
          puppet.manifest_file  = "node.pp"
          puppet.options = "--verbose --debug"
        end
      end
    end
  end
end
