name    'haraldsk-nfs'
version '1.1.1'
source 'git@github.com:haraldsk/puppet-module-nfs.git'
author 'haraldsk@redpill-linpro.com'
license 'Apache License, Version 2.0'
summary 'nfs client and server module'
description 'nfs client and server module'
project_page 'https://github.com/haraldsk/puppet-module-nfs'

dependency 'ripienaar-concat', '>= 0.2.0'
dependency 'puppetlabs-stdlib', '>= 3.0.1'

