require 'rake'
require 'rspec/core/rake_task'
require 'rubygems'
require 'puppet-lint/tasks/puppet-lint'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = 'spec/*/*_spec.rb'
end

task :test => [:spec, :lint]

task :default => :test
